server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: username
      password: password
      database: toyProject

  profiles:
    active: swagger, s3
  datasource:
    url: jdbc:h2:~/toyProject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

